name: ${{values.app_name}}-cicd

on:
  push:
    paths:
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      git_sha_short: ${{ steps.commit.outputs.short }}  
    steps:
      - id: commit
        uses: prompt/actions-commit-hash@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ '${{ secrets.DOCKERHUB_USERNAME }}' }}
          password: ${{ '${{ secrets.DOCKERHUB_TOKEN }}' }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: gkadam/${{values.app_name}}:${{ steps.commit.outputs.short }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Modify values file
        shell: bash
        run: | 
          echo ${{ '${{needs.ci.outputs.commit_id}}' }}
          sudo apt-get update && sudo apt-get install -y python3-pip
          sudo apt-get install -y python3-pip yq
          yq -Yi '.image.tag = "${{'${{needs.ci.outputs.commit_id}}'}}"' charts/${{values.app_name}}/values-${{values.app_env}}.yaml

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: 'Updates values.yaml with commit ${{ '${{needs.ci.outputs.commit_id}}' }}'
      
      - name: Install Argocd
        shell: bash
        run: |
          curl -ksSL -o argocd https://argocd-server.argocd/download/argocd-linux-amd64
          chmod +x argocd
          sudo mv ./argocd /usr/local/bin/argocd

      - name: argocd login
        shell: bash
        run: |
          argocd login argocd-server.argocd \
            --insecure  \
            --grpc-web \
            --username admin \
            --password  ${{ '${{ secrets.ARGOCD_PASSWORD }}' }}

      - name: Ensure argocd repo and app
        shell: bash
        run: |
          repo="https://github.com/missonganesh80/${{values.app_name}}.git"
          argocd repo list | grep -q $repo || argocd repo add $repo
          argocd app get ${{values.app_name}} || argocd app create ${{values.app_name}} \
            --repo $repo \
            --path charts/${{values.app_name}} \
            --dest-namespace ${{values.app_env}} \
            --dest-server https://kubernetes.default.svc \
            --values values-${{values.app_env}}.yaml \
            --revision main \
            --sync-policy manual \
            --sync-option CreateNamespace=true

      - name: Argocd app sync
        shell: bash
        run: |
          argocd app sync ${{values.app_name}}
